---
project_name: aro-rp-versions
env:
  - CGO_ENABLED=0
builds:
  - ldflags:
    - "-X {{.Env.VERSION_PKG}}.Branch={{.Env.BRANCH}}"
    - "-X {{.Env.VERSION_PKG}}.BuildDate={{.Env.DATE}}"
    - "-X {{.Env.VERSION_PKG}}.GitSHA1={{.Env.COMMIT}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
- replacements:
    amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: false
